### ISSUE TITLE
ESP Home Code - ESP32-S2 - Wemos Style - Notes

### ISSUE THREAD

**Issue by Joshndroid** [Mottramlabs/ESP32-4-Channel-Mains-Current-Sensor#5]
Hello all who may find this.

After obtaining the code provided in the other issue - https://github.com/Mottramlabs/ESP32-4-Channel-Mains-Current-Sensor/issues/1

I noticed that the ADC provided would list an error where it says 

`ESP32S2 doesn't support ADC on this pin.`

Knocking over a fair bit of googling, etc I couldn't get a grasp on it until i found that the ADC pins are slightly different.
Using this site here - https://www.studiopieters.nl/esp32-s2-pinout/

```
GPIO1  ADC1_CH0
GPIO2 ADC1_CH1
GPIO3 ADC1_CH2
GPIO4 ADC1_CH3

```

Don't use the ADC2 pins listed as these are disabled for wifi

Digging through some more within the schematics of the 4 port board https://github.com/Mottramlabs/ESP32-4-Channel-Mains-Current-Sensor/blob/main/SCH201191.pdf

It listed that the barrel jacks appear to go to 1, 2, 3 & 4.

![image](https://github.com/Mottramlabs/ESP32-4-Channel-Mains-Current-Sensor/assets/5584652/0f70a937-129d-49a5-9d14-7b553a839db5)

I updated that code to change the GPIO to 1,2,3 & 4 and it validated and got it installed no issues.

Next issue it appeared is that it seemed like the device would randomly disconnect...
Originally i thought it was a power issue but digging through some more docs on ESPHome (https://esphome.io/components/wifi.html) it appears that there is a 'light' power save feature with these so that it must turn off/on wifi. This may be okay later down the line but when your trying to set the device up it makes it super frustrating it just disconnecting. Under the wifi listed the power saving as none.

```
wifi:
  # ...
  power_save_mode: none
```

This has stopped it disconnecting after about 90 seconds or so... This may also assist in getting the dam thing to flash as this disconnect would be a pain in trying to flash it OTA wirelessly during my updates/changes to the yaml.

I have been typing this out for a fair while now and the device is yet to disconnect =]

I found it easier to set a static IP so i have done this in both my DHCP settings within the router but have also backed this up within the device yaml with this from https://esphome.io/components/wifi.html

```
wifi:
  # ...
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 10.0.0.42
    # Set this to the IP address of the router. Often ends with .1
    gateway: 10.0.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
```

When you watch the device connect however it does not have any DNS listed so the addition of a DNS1 & DNS2 parameter into the wifi section above below subnet will get you sorted (if necessary)

In essence your WiFi section within the yaml would end up looking something like this

```
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 10.0.0.42
    gateway: 10.0.0.1
    subnet: 255.255.255.0
    dns1: 10.0.0.1

  #powersaving WiFi
  power_save_mode: none
```

**I am yet to get this fully working or deployed but am using this a notes for getting through the issues as well as helping others who purchase it and have a bit of a WTF moment in trying to get it going.**

**Comment by dantheg1t** [comment]
Hi @Joshndroid 

I have aquired the same hardware as you and I thank you for the notes you have provided, helping to get this setup and working.

Have you managed to get this fully deployed or are you still having issues?

**Comment by Joshndroid** [comment]
Hi @dantheg1t

No I played around a little but have put it in the drawer for now.

Have you had any luck with it?

**Comment by dantheg1t** [comment]
> Hi @dantheg1t
> 
> No I played around a little but have put it in the drawer for now.
> 
> Have you had any luck with it? 

I am just in the process of getting things configured. Haven't had my CT's delivered yet, so early days.

**Comment by dantheg1t** [comment]
> Hi @dantheg1t
> 
> No I played around a little but have put it in the drawer for now.
> 
> Have you had any luck with it? 

So what are the remaining issues that you have?

**Comment by Joshndroid** [comment]
The device seems to go to sleep/off after a while and doesn't want to wake up.

Not sure what the configuration is to disable this. I don't quite understand why.

I put the clamp around my power cable for the pc Setup just to see if I could get a reading and it didn't seem like it.. But I think I need to sort the sleep thing first before I tackle the next bit

**Comment by jtenniswood** [comment]
I'm struggling to setup this device, have you had any joy getting it working? If yes, could you share your code!
Thanks!

**Comment by TheNeutrinoRaged** [comment]
Thanks for your thread, I got my eps32 s2 and 100/50ma sct working with home assistant (remotely with mqtt) by following along and referring back to issue #1 

I've put my tweaked code below, I actually bought a 4 port board but only have 1 Ct for now.


<details>
<summary>esphome code</summary>

```
esphome:
  name: esp32s2pm
  friendly_name: esp32s2pm

esp32:
  board: lolin_s2_mini
  framework:
    type: esp-idf

# Enable logging
logger:
  level: debug

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/London

interval:
  - interval: 5s
    then:
      - script.execute: readCTs
script:
  - id: readCTs
    then:
      - component.update: ct1Amps
      - delay: 500ms
      - component.update: ct1Watts
      - delay: 500ms

switch:
   - platform: restart
     name: "Restart"
   
sensor:
  - platform: ct_clamp
    sensor: adc_sensor_1
    name: ct1Amps
    id: ct1Amps
    update_interval: never
    sample_duration: 200ms
    filters:
        - calibrate_linear:
             method: exact
             datapoints:
                - 0 -> 0
                - 0.004 -> 0
                - 1.015 -> 100

  - platform: adc
    pin: GPIO1
    id: adc_sensor_1
    attenuation: 11db
    internal: true
  
  - platform: wifi_signal
    name: "wifi_signal"
    update_interval: 1min
  - platform: uptime
    name: "uptime"
    id: Uptime    
    update_interval: 1min

#Watts per channel
  - platform: template
    name: CT1 Watts
    id: ct1Watts
    lambda: return id(ct1Amps).state * 240;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: never

  - platform: total_daily_energy
    name: CT1 Total kWh
    power_id: ct1Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: "mdi:flash"
    
mqtt: <removed>
```

</details>
