### ISSUE TITLE
Non 0 values without CT clamps

### ISSUE THREAD

**Issue by uxieme** [Mottramlabs/ESP32-4-Channel-Mains-Current-Sensor#8]
Hi, 

Is everything fine with my board?
I am getting some weird numbers without any CT.
I see that most of the people here get 0, and I for some reason get 0.004, 0.003, 0.002A
 
[18:14:56][D][ct_clamp:041]: 'ct1Amps' - Raw AC Value: 0.003A after 472 different samples (2360 SPS)
[18:14:56][D][sensor:094]: 'ct1Amps': Sending state 0.00316 A with 2 decimals of accuracy

And it jumps all the time. 

Config: 
```
sensor:
  - platform: ct_clamp
    sensor: adc_sensor_1
    name: ct1Amps
    id: ct1Amps
    update_interval: 2s
    sample_duration: 200ms

  - platform: adc
    pin: GPIO34
    id: adc_sensor_1
    attenuation: 11db
    internal: true
```    

![PXL_20241128_171341579](https://github.com/user-attachments/assets/8140dd60-34da-48ca-9dc9-8e7ebdd854a1)
